travis test

diff --git a/.travis.yml b/.travis.yml
--- a/.travis.yml
+++ b/.travis.yml
@@ -1,34 +1,58 @@
 ---
-
-dist: 'trusty'
-
-env:
-  global:
-    - ANSIBLE_FORCE_COLOR: True
-    - ANSIBLE_LOG_PATH: './ansible.log'
-    - ANSIBLE_HOST_KEY_CHECKING: False
+sudo: required
+dist: trusty
 
 language: python
 python: "2.7"
 
-sudo: 'required'
+# Doc: https://docs.travis-ci.com/user/customizing-the-build#Build-Matrix
+env:
+  - ANSIBLE_VERSION: latest
+  - ANSIBLE_VERSION: 2.4.0.0
+  - ANSIBLE_VERSION: 2.3.2.0
+  - ANSIBLE_VERSION: 2.3.1.0
+  - ANSIBLE_VERSION: 2.3.0.0
+  - ANSIBLE_VERSION: 2.2.3.0
+  - ANSIBLE_VERSION: 2.2.2.0
+  - ANSIBLE_VERSION: 2.2.1.0
+  - ANSIBLE_VERSION: 2.2.0.0
+  - ANSIBLE_VERSION: 2.1.6.0
+  - ANSIBLE_VERSION: 2.1.5.0
+  - ANSIBLE_VERSION: 2.1.4.0
+  - ANSIBLE_VERSION: 2.1.3.0
+  - ANSIBLE_VERSION: 2.1.2.0
+  - ANSIBLE_VERSION: 2.1.1.0
+  - ANSIBLE_VERSION: 2.1.0.0
+  - ANSIBLE_VERSION: 2.0.2.0
+  - ANSIBLE_VERSION: 2.0.1.0
+  - ANSIBLE_VERSION: 2.0.0.2
+  - ANSIBLE_VERSION: 2.0.0.1
+  - ANSIBLE_VERSION: 1.9.6
+  - ANSIBLE_VERSION: 1.9.5
+  - ANSIBLE_VERSION: 1.9.4
 
-addons:
-  apt:
-    packages:
-    - python-pip
+branches:
+  only:
+    - master
+
+before_install:
+  - sudo apt-get update -qq
 
 install:
-  - pip install ansible
-  - ansible --version
+  # Install Ansible.
+  - if [ "$ANSIBLE_VERSION" = "latest" ]; then pip install ansible; else pip install ansible==$ANSIBLE_VERSION; fi
+  - if [ "$ANSIBLE_VERSION" = "latest" ]; then pip install ansible-lint; fi
   - |
     if [ -f tests/requirements.yml ]; then
-      ansible-galaxy install -r tests/requirements.yml --roles-path=/home/travis/build/eendroroy
+      ansible-galaxy install -r tests/requirements.yml --roles-path=/home/travis/.ansible/roles
     fi
-  - printf '[defaults]\nroles_path=../' > ansible.cfg
 
 script:
-  - ansible-playbook tests/test.yml -i tests/inventory
+  # Check the role/playbook's syntax.
+  - ansible-playbook -i tests/inventory tests/test.yml --syntax-check
 
-notifications:
-  webhooks: https://galaxy.ansible.com/api/v1/notifications/
+  # Run the role/playbook with ansible-playbook.
+  - ansible-playbook -i tests/inventory tests/test.yml -vvvv --skip-tags update,copy_host_ssh_id
+
+  # check is the user is created or not
+  - id -u tasdik | grep -q "no" && (echo "user not found" && exit 1) || (echo "user found" && exit 0)
